### PR TITLE
Change type of applicationId from Long to String

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

**Review by petrdvorak — APPROVED** [review]
Looks OK

**Comment by romanstrobl** [comment]
I would expect this PR to be opened in `enrollment-server`, not `enrollment-server-wultra`. We expect this change to propagate to all the other enrollment servers, right?

**Comment by romanstrobl** [comment]
Ah ok, I see, this issue was fixed in https://github.com/wultra/enrollment-server/pull/196. I believe we do not need to create a PR for this change, we just need to merge changes from the upstream `enrollment-server` repo.

**Comment by banterCZ** [comment]
Ok, let's do it as a merge from the upstream.

**Pull request closed without merging**
